### PR TITLE
Batch submission Kata from Alwan

### PR DESCRIPTION
**Pull request by alwanadi17**
Hi,

These are solutions Kata written in C and a bit written in C++, the Kata tagged fundamental.

Please pull,
thank you.

### CODE REVIEW

**Review by ammarfaizi2 — COMMENTED** [review]
Wordwrap the commit message at 72 chars next time.

**Comment by ammarfaizi2** [comment]
I pulled this, but wordwrap the commit message at 72 chars next time.

**Comment by ammarfaizi2** [comment]
I pulled this, but wordwrap the commit message at 72 chars next time.

**Comment by alwanadi17** [comment]
@ammarfaizi2 Just to make sure, is it on commits create README.txt?

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Just to make sure, is it on commits create README.txt?

Yes.

**Pull request merged**
