### PR TITLE
Batch codewars submissions from Ammar

### PR DESCRIPTION
**Pull request by ammarfaizi2**
Hi @Akiekano,

How are you? I hope you are well.

[ A bit story of my study progress ]

I don't know what can I do next year, but I want to improve things faster and faster.

So far I have been able to comprehend basic hiragana, although I sometimes forget it and have to reopen my textbook. I started touching katakana since yesterday. I know very few kanji characters. I can make basic sentences for introducing myself in Japanese. That is to say, my Japanese skill is not really good today. But I promise I will master it in the near future.

My plan is, looking for job in Japan, then go there and live there for couple of years.

I don't know when I can go to Japan. But I have started saving some of my salary for living in Japan. Relocating to Japan must be expensive, right?

While I have never met you in real life, I hope I can meet you face to face in Japan someday. Glad to meet you on Telegram.

As always, my support for you:
Please learn programming and computer architecture seriously. For programming language, my recommendation is C/C++, because it is common used in context of High-Performance Computing. But again, not strictly C/C++, you can do everything what you want to achieve your dream (as long as it is rational of course).

Wish me good mental health, my journey is a bit stressful :)

Best regards,
Ammar

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
Regarding codewars submission today. My codewars submissions are fully written in NASM x86-64.

Please pull!

```
----------------------------------------------------------------
The following changes since commit 6ac01be3b8132c6a90916cb61230a3678a97063b:

  README.md: update stats (2021-08-30 17:47:46 +0000)

are available in the Git repository at:

  https://github.com/ammarfaizi2/Competitive_Programing-ID late-submission-for-akiekano

for you to fetch changes up to fc63e62e7c7ad51b4803b111270431ffe34024fa:

  Merge https://github.com/Akiekano/Competitive_Programing-ID into late-submission-for-akiekano (2021-09-02 21:47:21 +0700)

----------------------------------------------------------------
Ammar Faizi (7):
      Codewars: add 7_kyu_borrower_speak
      Codewars/7_kyu_borrower_speak: add ammarfaizi2's solution in NASM x86
      Codewars: add 8_kyu_sum_of_positive
      Codewars/8_kyu_sum_of_positive: add ammarfaizi2's solution in NASM x86-64
      Codewars: add 8_kyu_abbreviate_a_two_word_name
      Codewars/8_kyu_abbreviate_a_two_word_name: add ammarfaizi2's solution in NASM x86-64
      Merge https://github.com/Akiekano/Competitive_Programing-ID into late-submission-for-akiekano

 .../7_kyu_borrower_speak/README.txt   | 15 ++++
 .../ammarfaizi2/solution.asm          | 62 ++++++++++++++
 .../README.txt                        | 13 +++
 .../ammarfaizi2/solution.asm          | 36 ++++++++
 .../8_kyu_sum_of_positive/README.txt  |  7 ++
 .../ammarfaizi2/solution.asm          | 25 ++++++
 6 files changed, 158 insertions(+)
 create mode 100644 Codewars/7_kyu_borrower_speak/README.txt
 create mode 100644 Codewars/7_kyu_borrower_speak/ammarfaizi2/solution.asm
 create mode 100644 Codewars/8_kyu_abbreviate_a_two_word_name/README.txt
 create mode 100644 Codewars/8_kyu_abbreviate_a_two_word_name/ammarfaizi2/solution.asm
 create mode 100644 Codewars/8_kyu_sum_of_positive/README.txt
 create mode 100644 Codewars/8_kyu_sum_of_positive/ammarfaizi2/solution.asm
```

**Comment by Akiekano** [comment]
@ammarfaizi2 > My plan is, find a job in Japan, then go there and live there for a few years.
This is very cool, I hope you can achieve it according to your target, yes in Japan it is expensive but I'm sure you can achieve it. I fully support, and congratulations on understanding in hiragana, you mastered it pretty quickly.

> Please learn programming and computer architecture seriously.
Of course, by the way this might start to become my culture, I always take the time to review the code" every day, I feel happy doing it. For the past few days I've been busy with lectures and hey if you're aware these few days I've been inactive on facebook.

> Wish me good mental health, my journey is a bit stressful :)
Ofc, but your journey was great it was very impressive to me, I hope one day I can be like you. and i can catch up with you in japan.

アりがとございました
じゃあ。おやすみ

**Comment by ammarfaizi2** [comment]
@Akiekano 

[ I need to teach you something about quoting someone's message (this applies on email and GitHub comment, and you better bring this habit everywhere), the correct way is, ">" followed by the quoted text, empty line, your reply. You always skip empty line. That is why your reply looks bad formatted on GitHub. See how I do it here. ]

> Of course, by the way this might start to become my culture, I always take the time to review the code" every day, I feel happy doing it. 

That's the spirit. You've changed a lot since I first met you. Now you need to beat me to win the battle! Come here and defeat me if you can ;)

> For the past few days I've been busy with lectures and hey if you're aware these few days I've been inactive on facebook

Yes, I am fully aware of that. I had always seen you on my Facebook homepage before, but I couldn't see you latety (I thought because you were sick).

Well, it is a good thing, Facebook could be dangerous and waste of time if you are not careful. Hopefully the reason behind that is something you do to be more productive.

[ Extra section, you may ignore this, not important. ]
BTW, the other day I when we talked about anime 86, I have downloaded batch episodes on my local machine, have watched 2 episodes and I started to get bored, I don't have much interest to continue watching it.

^ It can be a good thing too, as too much watching anime could be waste of time as well.

**Comment by Akiekano** [comment]
@ammarfaizi2 > the correct way is, ">" followed by the quoted text, empty line, your reply.
なるほどせつめいしていただきありがとございます。

> Well, it is a good thing, Facebook could be dangerous and waste of time if you are not careful.
Yes, that's very true, I think Facebook is too indulgent for its users to lose track of time.

> have watched 2 episodes and I started to get bored
ahhhh i remember, i guess you finished and (probably) simp the female mc lol.

**Pull request merged**
