### PR TITLE
Add one solution kata from Alwan

### PR DESCRIPTION
**Pull request by alwanadi17**
Hi,

Here is a kata, written in C++. The kata is about math and fundamental, I really enjoy this one.

Please pull,
thank you

### CODE REVIEW

**Comment by Akiekano** [comment]
@alwanadi17 @ammarfaizi2 how are you?

**Comment by ammarfaizi2** [comment]
On Thu, Nov 4, 2021 at 5:12 AM Die Several Times.
***@***.*** wrote:
>
> @alwanadi17 @ammarfaizi2 how are you?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Akiekano/Competitive_Programing-ID/pull/58#issuecomment-960217840

Hello,

I am sick. I vomited several times yesterday. Now I don't feel good
for eating, recently I only eat once / twice a day. I am still having
a fever, but I think my temperature is better than last week. I take
bed rest all day long, but I can't fully leave my laptop. I still
write code and check email, so I pulled this PR yesterday. That's the
summary of what I've been doing recently.

Finally I have a "hard time" when living alone. But after all, I am
still grateful I can have food and water come to me without getting
myself out from home (this is the part that I love and keep me alive).
I think after I recover from this, I should go outside and start
talking with real people face to face around me.

That's all. Now, how are you? I hope you're well.

P.S.: I am still active on email. Send me something.

For confidential stuff, you can encrypt it with GPG before sending. As
always, my public keys can be found here:
https://github.com/ammarfaizi2.gpg

**Comment by Akiekano** [comment]
@ammarfaizi2 Sorry I replied to you via the telegram bot reply feature again.

I'm sad to hear from you, I hope you get well soon, maybe it's better if you ask a friend ro accompany you? or whoever it is. how do you get food? gofood?
Many people worry about you especially the gnuweeb.

I'm fine, thanks for asking, it's just that I have problems with emotional, even for a while ago I thought that dying is better than living, I hope I don't experience the same thing a second time.

 Are you still using gnuweeb mail? I want to ask about some things regarding C.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Sorry I replied to you via the telegram bot reply feature again.

I don't see any difference, that reply feature seems to work just fine.

> I'm sad to hear from you, I hope you get well soon

Thanks!

> maybe it's better if you ask a friend ro accompany you? or whoever it is.

I don't feel comfortable doing that unless I have a close friend near me. But that does not happen today.

But anyway, I believe one more extra week for me to recover is enough. I can survive at home. I still have a lot of resources to get life at home. I can manage food and water. I still can walk to take a bath. I still can make money.

I think I have been progressing gradually towards good health, and today I feel better than yesterday.

> how do you get food? gofood?

Yes.

> Many people worry about you especially the gnuweeb.
> 
> I'm fine, thanks for asking, it's just that I have problems with emotional, even for a while ago I thought that dying is better than living, I hope I don't experience the same thing a second time.

No, please don't be like that again. I can support you, but please let me know your problem so that I can know your bad condition. For that case, don't wait for me to ask your condition, just share your problem anytime. Enjoy!

>  Are you still using gnuweeb mail? I want to ask about some things regarding C.

Yes, I still use it. You can always send me email anytime. I may just defer the response. I just want to lay on bed and prepare to sleep.

**Pull request merged**
