### PR TITLE
Add codewars kata and other submission from Ananda

### PR DESCRIPTION
**Pull request by anandadwipra**
This is my First Codewars submision 4_kyu from me,Please pull and review it ?
Thanks .

### CODE REVIEW

**Comment by Akiekano** [comment]
@anandadwipra Let me check it first.

**Comment by Akiekano** [comment]
@anandadwipra Anyway do you know @ammarfaizi2 ? I haven't seen him for a few days.

**Comment by anandadwipra** [comment]
HI @Akiekano .
I don't know, the last time I communicated with him was on the 28th

**Comment by ammarfaizi2** [comment]
On Sun, Oct 31, 2021 at 6:44 AM Die Several Times. <notifications@github.com> wrote:
>
> @anandadwipra Anyway do you know @ammarfaizi2 ? I haven't seen him for a few days.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Hello,

Sorry for not giving any update. I have not been so productive lately. I got sick since last week. I am not sure what happened to me. I rarely get out from home, but recently I got fever and couldn't sleep well. I strictly limit my activities and avoid stressful problem as much as possible.

Telegram has been causing mental and emotional stress, so I close it temporarily. I don't want these stuff interfere with my health.

I will be back later. Please take care of my Telegram groups where you're an admin.

Ciao.

**Comment by Akiekano** [comment]
@ammarfaizi2 I'm sad to hear that, I hope you get well soon, well I will take care of it, btw many are looking for you.

**Comment by alwanadi17** [comment]
@ammarfaizi2 Hi Sir Ammar,

Thank you for letting us know. I feel happy to hear from you. Take care and take some warm tea, but I will suggest you green tea or unsweetened chocolate. Just my preferences, don't think about it haha.

Regards,
Alwan

**Pull request merged**
